#!/usr/bin/env node
/**
 * gen-dts.js — generate a minimal `src/index.d.ts` from JSDoc comments.
 *
 * Usage:
 *   npm run gen-dts
 *   or: node scripts/gen-dts.js
 */
// simple generator: scans src/**/*.js for exported functions/constants
// and writes a minimal index.d.ts.  Not comprehensive but enough for most
// purposes; rerun with `npm run gen-dts` after adding new exports.

import fs from 'fs'
import { sync as globSync } from 'glob'
import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const cpPkg = require('comment-parser')
console.error('comment-parser pkg', cpPkg)
const parse = cpPkg.parse || cpPkg

// helper to convert JSDoc type to TS type (very basic)
function jsdocTypeToTs(t) {
  if (!t) return 'any'
  let s = String(t).trim()
  // if the entire type is wrapped in a single pair of braces, unwrap it
  if (/^\{[^{}]*\}$/.test(s)) {
    s = s.slice(1, -1).trim()
  }
  const low = s.toLowerCase()
  if (low === 'string' || low === 'number' || low === 'boolean' || low === 'any' || low === 'object' || low === 'void' || low === 'null' || low === 'undefined') {
    // JSDoc "Object" should map to lowercase object
    if (low === 'object') return 'object'
    return low
  }
  // convert generic Object<k,v> to Record<k,v>; conversion of Array already handled above
  if (/^[A-Za-z0-9_]+\[\]$/.test(s)) {
    return s
  }
  if (/^array<.*>$/.test(low)) {
    return s.replace(/^array<(.*)>$/i, '$1[]')
  }
  if (s.startsWith('Object<')) {
    // simple blanket conversion; leaves nested generics intact
    return s.replace(/^Object</, 'Record<')
  }
  if (/^function$/i.test(s)) {
    return '(...args:any[])=>any'
  }
  if (/^[A-Za-z0-9_]+<.*>$/.test(s)) {
    return s
  }
  if (s.includes('|')) {
    // leave union untouched, may contain braces
    return s
  }
  // avoid wrapping function-signature types like `(x:number)=>string`
  if (s.includes('=>')) {
    return s
  }
  if (s.includes(':') && !s.trim().startsWith('{')) {
    return `{${s}}`
  }
  return 'any'
}

let decls = []
// track names we've declared globally to avoid duplicates
const globalSeen = new Set()

// manual header definitions (kept in sync by script)
decls.push(`// Type definitions for nimbiCMS_pre`
+ "\n// Generated by scripts/gen-dts.js; run \`npm run gen-dts\` to refresh\n"
)

// include some core types/interfaces that cannot be inferred easily
const manualTypes = `
export type ThemeStyle = 'light' | 'dark'

export interface InitOptions {
  el: string | Element
  contentPath?: string
  crawlMaxQueue?: number
  searchIndex?: boolean
  cacheTtlMinutes?: number
  defaultStyle?: ThemeStyle
  bulmaCustomize?: string
  lang?: string
  l10nFile?: string | null
  /** optional array of markdown paths provided by the host (example plugin)
   *  used by slug resolution and search index */
  markdownPaths?: string[]
}

export interface PageContext {
  data: Record<string, any>
  pagePath: string
  anchor: string | null
}

export interface HookContext {
  // common fields provided to all hooks
  pagePath?: string
  anchor?: string | null
  article?: HTMLElement
  toc?: HTMLElement
  topH1?: HTMLElement | null
  h1Text?: string | null
  slugKey?: string | null
  data?: Record<string, any>
  contentWrap?: HTMLElement | null
  navWrap?: HTMLElement | null
  // nav-build specific
  navbar?: HTMLElement
  linkEls?: NodeListOf<HTMLAnchorElement>
  contentBase?: string
}

// UI helper option and return shapes (mirrors src/ui.js typedefs)
export type UIOptions = {
  contentWrap: HTMLElement,
  navWrap: HTMLElement,
  container: HTMLElement,
  mountOverlay?: HTMLElement | null,
  t: (key: string, vars?: Object)=>string,
  contentBase: string,
  homePage: string,
  initialDocumentTitle: string,
  runHooks: (name: string, ctx?: Object)=>void|Promise<void>
}

export type UIReturn = {
  renderByQuery: () => Promise<void>,
  siteNav: object,
  getCurrentPagePath: () => string | null
}

// Router resolution cache types
export type ResolutionRecord = { value: { resolved: string, anchor: string | null }, ts: number }
export const RESOLUTION_CACHE_MAX: number
export const RESOLUTION_CACHE_TTL: number
export function setResolutionCacheMax(n: number): void
export function setResolutionCacheTtl(ms: number): void
export const resolutionCache: Map<string, ResolutionRecord>

// Fetch result and localization entry shapes (from slugManager and l10n defaults)
export type FetchResult = { raw: string, isHtml?: boolean, status?: number }
export type L10nEntry = { navigation: string, onThisPage: string, home: string, scrollToTop: string, readingTime: string, searchPlaceholder: string }

// primary entrypoint – options object is strongly typed above
export function initCMS(options: InitOptions): Promise<void>
export default initCMS

// hook / plugin API definitions
export function addHook(name: string, fn: (ctx:HookContext)=>void|Promise<void>): void
export function onPageLoad(fn: (ctx:HookContext)=>void|Promise<void>): void
export function onNavBuild(fn: (ctx:HookContext)=>void|Promise<void>): void
export function transformHtml(fn: (ctx:HookContext)=>void|Promise<void>): void
export function _clearHooks(): void

export type WorkerManager = {
  get: () => Worker | null
  send: (msg: any, timeout?: number) => Promise<unknown>
  terminate: () => void
}

// Worker manager helpers
export function makeWorkerManager(createWorker: () => Worker|null, name?: string): WorkerManager
export function createWorkerFromRaw(code: string): Worker|null

// UI helper (opaque options for now)
export function createUI(opts: UIOptions): UIReturn

// Slug manager shared maps
export const slugToMd: Map<string, string|{default?:string,langs?:Record<string,string>}>
export const mdToSlug: Map<string,string>
export const availableLanguages: string[]
export const listPathsFetched: Set<string>
export const listSlugCache: Map<string,string>
export const searchIndex: Array<{slug:string,title:string,excerpt:string,path:string}>

// Codeblocks
export const SUPPORTED_HLJS_MAP: Map<string,string>

// Additional explicit declarations to reduce remaining any entries
export function setLanguages(list: string[]): void
export function buildSearchIndexWorker(contentBase: string): Promise<Array<{slug:string,title:string,excerpt:string,path:string}>>
export function crawlForSlugWorker(slug: string, base: string, maxQueue: number): Promise<string|null>
export function removeSlugResolver(fn: (slug:string)=>unknown): void
export function setNotFoundPage(p: string): void
export function _setAllMd(obj: Record<string,string>): void
export function clearListCaches(): void
export function clearFetchCache(): void
export function fetchMarkdown(path: string, base?: string): Promise<FetchResult>

`
// Additional manual augmentations for htmlBuilder, nav, markdown, and seo
const extraManual = `
export type NavTreeItem = { path: string, name: string, isIndex?: boolean, children?: NavTreeItem[] }
export type NavBuildResult = { navbar: HTMLElement, linkEls: NodeListOf<Element> }
export function createSiteNav(homePage: string): NavTreeItem[]
export function buildNav(navbarWrap: HTMLElement, container: HTMLElement, navHtml: string, contentBase: string, homePage: string, t: (key:string, vars?:Record<string,unknown>)=>string, renderByQuery: ()=>void, effectiveSearchEnabled: boolean, searchIndexMode: 'eager'|'lazy'): Promise<NavBuildResult>

export type NavItem = { path: string, name: string, children?: NavItem[] }
export type TocEntry = { level:number, text:string, id?:string }
export type ParsedPage = { html: string, meta: object, toc: TocEntry[] }
export type ArticleResult = { article: HTMLElement, parsed: ParsedPage, toc: HTMLElement, topH1: HTMLElement | null, h1Text: string | null, slugKey: string | null }
export function createNavTree(t: (key:string, vars?:Record<string,unknown>)=>string, tree: NavItem[]): HTMLElement
export function buildTocElement(t: (key:string)=>string, toc: TocEntry[], pagePath?: string): HTMLElement
export function prepareArticle(t: (key:string)=>string, data: {raw:string,isHtml?:boolean}, pagePath: string, anchor: string|null, contentBase: string): Promise<ArticleResult>
export function initAnchorWorker(): Worker|null
export function rewriteAnchorsWorker(article: HTMLElement, contentBase: string, pagePath?: string): Promise<void>
export function attachTocClickHandler(toc: HTMLElement): void
export function scrollToAnchorOrTop(anchor: string|null): void
export function ensureScrollTopButton(article: HTMLElement, topH1: HTMLElement|null, opts?: { mountOverlay?: HTMLElement|null, container?: HTMLElement|null, mountEl?: HTMLElement|null, navWrap?: HTMLElement|null, t?: Function }): void

export type MarkdownPlugin = { tokenizer?: Function, renderer?: object, walkTokens?: Function, transform?: Function }
export const markdownPlugins: MarkdownPlugin[]
export function addMarkdownExtension(plugin: MarkdownPlugin): void
export function setMarkdownExtensions(plugins: MarkdownPlugin[]): void
export function initRendererWorker(): Worker|null
export function parseMarkdownToHtml(md: string): Promise<ParsedPage>
export function detectFenceLanguages(md: string, supportedMap?: Map<string,string>): Set<string>

export const currentLang: string
export function t(key: string, replacements?: Record<string,string>): string

export function setTag(name: string, content: string): void
export function setMetaTags(data: Record<string,unknown>, titleOverride?: string, imageOverride?: string, descOverride?: string, initialDocumentTitle?: string): void
export function setStructuredData(data: Record<string,unknown>, pagePath: string, titleOverride?: string, imageOverride?: string, descOverride?: string, initialDocumentTitle?: string): void
export function applyPageMeta(t: (key:string, vars?:Record<string,unknown>)=>string, initialDocumentTitle: string, parsed: ParsedPage, toc: TocEntry[], article: HTMLElement, pagePath: string, anchor: string|null, topH1: HTMLElement|null, h1Text: string|null, slugKey: string|null, data: Record<string,unknown>): void

export function setLazyload(img: HTMLImageElement): void
export function joinPaths(...parts: string[]): string

`
// add router and slug-manager explicit types to reduce `any` residues
const extraRouterSlug = `
export function _clearIndexCache(): void
export function refreshIndexPaths(): void
export function _purgeExpiredEntries(): void
export function buildPageCandidates(resolved: string): string[]
export function fetchPageData(raw: string, contentBase: string): Promise<{data: Record<string, any>, pagePath: string, anchor: string | null}>

export function initSlugWorker(): Worker|null
export function addSlugResolver(fn: (slug:string,contentBase?:string)=>Promise<string|null>|string|null): void
export const notFoundPage: string
export function setContentBase(contentBase: string): void
export function slugify(s: string): string
export function resolveSlugPath(slug: string): string|null
export const crawlCache: Map<string, Promise<string|null>|string|null>
export function buildSearchIndex(contentBase: string): Promise<Array<{slug:string,title:string,excerpt:string,path:string}>>
export function setDefaultCrawlMaxQueue(n: number): void
export const crawlForSlug: (decoded: string, contentBase: string, maxQueue?: number) => Promise<string|null>
export function crawlAllMarkdown(contentBase: string, maxQueue: number): Promise<string[]>
export function ensureSlug(decoded: string, contentBase: string, maxQueue: any): Promise<string|null>
`

decls.push(extraManual);
decls.push(extraRouterSlug);
decls.push(manualTypes);
// record that we've already declared these manual symbols to avoid later duplicates
[
  'initCMS','addHook','onPageLoad','onNavBuild','transformHtml','_clearHooks',
  'makeWorkerManager','createWorkerFromRaw','createUI',
  // slug/paths/search helpers
  'slugToMd','mdToSlug','availableLanguages','listPathsFetched','listSlugCache','searchIndex',
  'SUPPORTED_HLJS_MAP','fetchMarkdown','fetchCache','resolutionCache','RESOLUTION_CACHE_TTL',
  'RESOLUTION_CACHE_MAX',
  'setResolutionCacheMax','setResolutionCacheTtl','resolutionCacheGet','resolutionCacheSet',
  // htmlBuilder/nav/manual extras
  'createSiteNav','buildNav','createNavTree','buildTocElement','prepareArticle',
  'initAnchorWorker','rewriteAnchorsWorker','attachTocClickHandler','scrollToAnchorOrTop','ensureScrollTopButton',
  // markdown extras
  'MarkdownPlugin','markdownPlugins','addMarkdownExtension','setMarkdownExtensions','initRendererWorker','parseMarkdownToHtml','detectFenceLanguages',
  // l10n/seo helpers
  'currentLang','t','setTag','setMetaTags','setStructuredData','applyPageMeta','setLazyload','joinPaths',
  // router & slug manager
  '_clearIndexCache','refreshIndexPaths','_purgeExpiredEntries','buildPageCandidates','fetchPageData',
  'initSlugWorker','addSlugResolver','notFoundPage','setContentBase','slugify','resolveSlugPath','crawlCache','buildSearchIndex','setDefaultCrawlMaxQueue','crawlForSlug','crawlAllMarkdown','ensureSlug',
  // slug manager runtime helpers
  'setLanguages','buildSearchIndexWorker','crawlForSlugWorker','removeSlugResolver','setNotFoundPage','_setAllMd','clearListCaches','clearFetchCache'
].forEach(n=>globalSeen.add(n))

globSync('src/**/*.js').forEach(file => {
  // add a header comment so users can see where these symbols originate
  decls.push(`\n// --- from ${file}`)

  const src = fs.readFileSync(file, 'utf8')
  const comments = parse(src, { spacing: 'preserve' })

  // we track names we've declared to avoid duplicates (per-file), and
  // consult `globalSeen` to avoid duplicates across files/manual types
  const seen = new Set()

  // helper to add a declaration if not already present
  function addDecl(name, d) {
    if (!seen.has(name) && !globalSeen.has(name)) {
      seen.add(name)
      globalSeen.add(name)
      decls.push(d)
    }
  }

  // pre-split source lines once for comment indexing
  const srcLines = src.split('\n')
  comments.forEach(c => {
    if (!c.line) return
    // compute position of the start of the comment based on line number
    const idx = srcLines.slice(0, c.line - 1).join('\n').length
    let endIdx = src.indexOf('*/', idx)
    if (endIdx === -1) {
      endIdx = idx
    } else {
      endIdx += 2
    }
    // only examine a small window after the comment so we don't
    // accidentally pick up an export that appears much later in the file.
    const after = src.slice(endIdx, endIdx + 500)

    const funcMatch = after.match(/export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/)
    if (funcMatch) {
      const name = funcMatch[1]
      if (name === 'initCMS') {
        // already declared manually above
      } else {
        let params = []
        if (funcMatch[2].includes('{') || funcMatch[2].includes('[')) {
          // destructured or option object; treat as single opts parameter
          params = ['opts']
        } else {
          params = funcMatch[2].split(',').map(p=>p.trim()).filter(p=>p)
        }
        const jsdocParams = {}
        c.tags.filter(t=>t.tag==='param').forEach(t=>{
          jsdocParams[t.name] = jsdocTypeToTs(t.type)
        })
        const retTag = c.tags.find(t=>t.tag==='returns' || t.tag==='return')
        let retType = 'any'
        if (retTag) {
          const raw = String(retTag.type || '')
          // determine if there is a *top-level* union (pipe not nested inside
          // braces, parentheses, or generic angle brackets).
          function hasTopUnion(str) {
            let depth = 0
            for (const ch of str) {
              if (ch === '{' || ch === '(' || ch === '<') depth++
              else if (ch === '}' || ch === ')' || ch === '>') depth--
              else if (ch === '|' && depth === 0) return true
            }
            return false
          }
          if (hasTopUnion(raw)) {
            // keep union intact, maybe wrap first object element
            retType = raw
            if (retType.startsWith('{') && !retType.startsWith('{\{') && !retType.includes('}|')) {
              // if the entire expression is a single braced value with no union, strip
              retType = retType.replace(/^\{|\}$/g, '')
            }
            // ensure that any unwrapped object part before a pipe is braced
            const parts = retType.split('|')
            parts[0] = parts[0].trim()
            if (parts[0].includes(':') && !parts[0].trim().startsWith('{')) {
              parts[0] = `{${parts[0]}}`
            }
            retType = parts.join('|')
          } else {
            // not a top-level union, fall back to standard conversion
            retType = jsdocTypeToTs(raw)
          }
          // normalize any remaining bare Object references to lowercase
          if (retType.includes('Object')) {
            retType = retType.replace(/\bObject\b/g, 'object')
          }
        }
        // helper to clean individual parameter type string
        function sanitizeParamType(typeStr) {
          let ty = String(typeStr || '').trim()
          // don't modify function types or types containing arrows
          if (ty.includes('=>')) return ty
          // wrap object-like annotations if not already braced
          if (ty.match(/[:].+/) && !ty.startsWith('{') && !ty.endsWith('}')) {
            ty = `{${ty}}`
          }
          // bare Array -> any[]
          ty = ty.replace(/\bArray\b/g, 'any[]')
          // normalize Object to lowercase
          ty = ty.replace(/\bObject\b/g, 'object')
          return ty
        }
        const paramStr = params.map(p => {
          let pname = p.replace(/=.*$/,'').trim()
          if (pname.startsWith('{') || pname.startsWith('[')) {
            pname = 'opts'
          }
          const rawType = jsdocParams[pname] || 'any'
          const finalType = sanitizeParamType(rawType)
          return `${pname}: ${finalType}`
        }).join(', ')
        // build basic declaration
        let decl = `export function ${name}(${paramStr}): ${retType}`
        // we no longer need regex-based sanitization of the entire decl
        addDecl(name, decl)
      }
    }
    const constMatch = after.match(/export\s+(?:const|let|var)\s+(\w+)\s*=/)
    if (constMatch) {
      const name = constMatch[1]
      // check for an @type tag on the preceding JSDoc comment
      const typeTag = c.tags.find(t => t.tag === 'type')
      if (typeTag && typeTag.type) {
        const tsType = jsdocTypeToTs(typeTag.type)
        addDecl(name, `export const ${name}: ${tsType}`)
      } else {
        addDecl(name, `export const ${name}: any`)
      }
    }
  })

  // now catch any remaining exports that weren't preceded by JSDoc
  // simple regexes for functions, constants, classes, default
  // if any exports were missed by preceding comment scan, fall back to
  // regex detection.  we already inserted a file header above.
  const exportRegexes = [
    // capture parameters in group 2 too
    /export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/g,
    /export\s+(?:const|let|var)\s+(\w+)/g,
    /export\s+class\s+(\w+)/g,
    /export\s+default\s+function(?:\s+(\w+))?/g,
    /export\s+default\s+(?:\w+)/g
  ]
  exportRegexes.forEach(re => {
    let m
    while ((m = re.exec(src)) !== null) {
      const name = m[1] || 'default'
      if (seen.has(name)) continue
      if (re === exportRegexes[0]) {
        // m[2] contains comma-separated params; if it contains a
        // destructuring brace we just collapse to a single "opts: any"
        let paramList = ''
        if (m[2].includes('{')) {
          paramList = 'opts: any'
        } else {
          paramList = (m[2] || '')
            .split(',')
            .map(p=>p.trim())
            .filter(p=>p)
            .map(p=>{
              const pname = p.replace(/=.*$/,'').trim()
              return `${pname}: any`
            })
            .join(', ')
        }
        addDecl(`export function ${name}(${paramList}): any`)
      } else if (re === exportRegexes[1]) {
        addDecl(`export const ${name}: any`)
      } else if (re === exportRegexes[2]) {
        addDecl(`export class ${name} {}`)
      } else if (re === exportRegexes[3]) {
        addDecl(`export default function ${name ? name : ''}(...args:any[]): any`)
      } else if (re === exportRegexes[4]) {
        // default export of something else; ignore
        addDecl(`export default any`)
      }
    }
  })
})

// make sure manualTypes (which contains the hook API lines) is present
if (!decls.includes(manualTypes)) {
  decls.unshift(manualTypes)
}
fs.writeFileSync('src/index.d.ts', decls.join('\n') + '\n')
console.log('wrote src/index.d.ts')
