#!/usr/bin/env node
// simple generator: scans src/**/*.js for exported functions/constants
// and writes a minimal index.d.ts.  Not comprehensive but enough for most
// purposes; rerun with `npm run gen-dts` after adding new exports.

import fs from 'fs'
import { sync as globSync } from 'glob'
import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const cpPkg = require('comment-parser')
console.error('comment-parser pkg', cpPkg)
const parse = cpPkg.parse || cpPkg

// helper to convert JSDoc type to TS type (very basic)
function jsdocTypeToTs(t) {
  if (!t) return 'any'
  let s = String(t).trim()
  // if the entire type is wrapped in a single pair of braces, unwrap it
  if (/^\{[^{}]*\}$/.test(s)) {
    s = s.slice(1, -1).trim()
  }
  const low = s.toLowerCase()
  if (low === 'string' || low === 'number' || low === 'boolean' || low === 'any' || low === 'object') {
    return low
  }
  if (/^[A-Za-z0-9_]+\[\]$/.test(s)) {
    return s
  }
  if (/^array<.*>$/.test(low)) {
    return s.replace(/^array<(.*)>$/i, '$1[]')
  }
  if (/^[A-Za-z0-9_]+<.*>$/.test(s)) {
    return s
  }
  if (s.includes('|')) {
    // leave union untouched, may contain braces
    return s
  }
  if (s.includes(':') && !s.trim().startsWith('{')) {
    return `{${s}}`
  }
  return 'any'
}

let decls = []
// track names we've declared globally to avoid duplicates
const seen = new Set()

// manual header definitions (kept in sync by script)
decls.push(`// Type definitions for nimbiCMS_pre`
+ "\n// Generated by scripts/gen-dts.js; run \`npm run gen-dts\` to refresh\n"
)

// include some core types/interfaces that cannot be inferred easily
const manualTypes = `
export type ThemeStyle = 'light' | 'dark'

export interface InitOptions {
  el: string | Element
  contentPath?: string
  defaultStyle?: ThemeStyle
  bulmaCustomize?: string
  lang?: string
  l10nFile?: string | null
  /** optional array of markdown paths provided by the host (example plugin)
   *  used by slug resolution and search index */
  markdownPaths?: string[]
}

export interface PageContext {
  data: any
  pagePath: string
  anchor: string | null
}

export interface HookContext {
  // common fields provided to all hooks
  pagePath?: string
  anchor?: string | null
  article?: HTMLElement
  toc?: HTMLElement
  topH1?: HTMLElement | null
  h1Text?: string | null
  slugKey?: string | null
  data?: any
  contentWrap?: HTMLElement | null
  navWrap?: HTMLElement | null
  // nav-build specific
  navbar?: HTMLElement
  linkEls?: NodeListOf<HTMLAnchorElement>
  contentBase?: string
}

// primary entrypoint – options object is strongly typed above
export function initCMS(options: InitOptions): Promise<void>
export default initCMS
`
decls.push(manualTypes)
// record that we've already declared initCMS to avoid later duplicates
seen.add('initCMS')

globSync('src/**/*.js').forEach(file => {
  const src = fs.readFileSync(file, 'utf8')
  const comments = parse(src, { spacing: 'preserve' })

  // we track names we've declared to avoid duplicates
  const seen = new Set()

  // helper to add a declaration if not already present
  function addDecl(name, d) {
    if (!seen.has(name)) {
      seen.add(name)
      decls.push(d)
    }
  }

  // pre-split source lines once for comment indexing
  const srcLines = src.split('\n')
  comments.forEach(c => {
    if (!c.line) return
    // compute position of the start of the comment based on line number
    const idx = srcLines.slice(0, c.line - 1).join('\n').length
    let endIdx = src.indexOf('*/', idx)
    if (endIdx === -1) {
      endIdx = idx
    } else {
      endIdx += 2
    }
    // only examine a small window after the comment so we don't
    // accidentally pick up an export that appears much later in the file.
    const after = src.slice(endIdx, endIdx + 500)

    const funcMatch = after.match(/export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/)
    if (funcMatch) {
      const name = funcMatch[1]
      if (name === 'initCMS') {
        // already declared manually above
      } else {
        const params = funcMatch[2].split(',').map(p=>p.trim()).filter(p=>p)
        const jsdocParams = {}
        c.tags.filter(t=>t.tag==='param').forEach(t=>{
          jsdocParams[t.name] = jsdocTypeToTs(t.type)
        })
        const retTag = c.tags.find(t=>t.tag==='returns' || t.tag==='return')
        let retType = 'any'
        if (retTag) {
          const raw = String(retTag.type || '')
          // determine if there is a *top-level* union (pipe not nested inside braces)
          function hasTopUnion(str) {
            let depth = 0
            for (const ch of str) {
              if (ch === '{' || ch === '(') depth++
              else if (ch === '}' || ch === ')') depth--
              else if (ch === '|' && depth === 0) return true
            }
            return false
          }
          if (hasTopUnion(raw)) {
            // keep union intact, maybe wrap first object element
            retType = raw
            if (retType.startsWith('{') && !retType.startsWith('{\{') && !retType.includes('}|')) {
              // if the entire expression is a single braced value with no union, strip
              retType = retType.replace(/^\{|\}$/g, '')
            }
            // ensure that any unwrapped object part before a pipe is braced
            const parts = retType.split('|')
            parts[0] = parts[0].trim()
            if (parts[0].includes(':') && !parts[0].trim().startsWith('{')) {
              parts[0] = `{${parts[0]}}`
            }
            retType = parts.join('|')
          } else {
            // not a top-level union, fall back to standard conversion
            retType = jsdocTypeToTs(raw)
          }
        }
        const paramStr = params.map(p => {
          let pname = p.replace(/=.*$/,'').trim()
          if (pname.startsWith('{') || pname.startsWith('[')) {
            pname = 'opts'
          }
          return `${pname}: ${jsdocParams[pname]||'any'}`
        }).join(', ')
        // build basic declaration
      let decl = `export function ${name}(${paramStr}): ${retType}`
      // separate params from return type to avoid mangling the latter
      const splitIndex = decl.indexOf('):')
      if (splitIndex !== -1) {
        const before = decl.slice(0, splitIndex+2) // include '):'
        const after = decl.slice(splitIndex+2)    // return type onward
        const sanitizedParams = before.replace(/:(\s*)([^,\)]+)/g, (m,p1,t) => {
          let ty = t.trim()
          if (ty.match(/[:].+/) && !ty.startsWith('{') && !ty.endsWith('}')) {
            ty = `{${ty}}`
          }
          ty = ty.replace(/\bArray\b/g, 'any[]')
          return ':' + p1 + ty
        })
        decl = sanitizedParams + after
      } else {
        // fallback: sanitize entire string but avoid touching generics
        decl = decl.replace(/:(\s*)([^,\)]+)/g, (m,p1,t) => {
          let ty = t.trim()
          if (ty.match(/[:].+/) && !ty.startsWith('{') && !ty.endsWith('}')) {
            ty = `{${ty}}`
          }
          ty = ty.replace(/\bArray\b/g, 'any[]')
          return ':' + p1 + ty
        })
      }
      addDecl(name, decl)
      }
    }
    const constMatch = after.match(/export\s+(?:const|let|var)\s+(\w+)\s*=/)
    if (constMatch) {
      const name = constMatch[1]
      addDecl(name, `export const ${name}: any`)
    }
  })

  // now catch any remaining exports that weren't preceded by JSDoc
  // simple regexes for functions, constants, classes, default
  const exportRegexes = [
    // capture parameters in group 2 too
    /export\s+(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)/g,
    /export\s+(?:const|let|var)\s+(\w+)/g,
    /export\s+class\s+(\w+)/g,
    /export\s+default\s+function(?:\s+(\w+))?/g,
    /export\s+default\s+(?:\w+)/g
  ]
  exportRegexes.forEach(re => {
    let m
    while ((m = re.exec(src)) !== null) {
      const name = m[1] || 'default'
      if (seen.has(name)) continue
      if (re === exportRegexes[0]) {
        // m[2] contains comma-separated params; if it contains a
        // destructuring brace we just collapse to a single "opts: any"
        let paramList = ''
        if (m[2].includes('{')) {
          paramList = 'opts: any'
        } else {
          paramList = (m[2] || '')
            .split(',')
            .map(p=>p.trim())
            .filter(p=>p)
            .map(p=>{
              const pname = p.replace(/=.*$/,'').trim()
              return `${pname}: any`
            })
            .join(', ')
        }
        addDecl(`export function ${name}(${paramList}): any`)
      } else if (re === exportRegexes[1]) {
        addDecl(`export const ${name}: any`)
      } else if (re === exportRegexes[2]) {
        addDecl(`export class ${name} {}`)
      } else if (re === exportRegexes[3]) {
        addDecl(`export default function ${name ? name : ''}(...args:any[]): any`)
      } else if (re === exportRegexes[4]) {
        // default export of something else; ignore
        addDecl(`export default any`)
      }
    }
  })
})

fs.writeFileSync('src/index.d.ts', decls.join('\n') + '\n')
console.log('wrote src/index.d.ts')
