/**
 * Type tests for the generated public API surface.
 *
 * `npm run type-test` runs `tsd` against `src/index.d.ts`. These assertions
 * pin the shapes that consumers depend on, so a JSDoc change that silently
 * widens or narrows a public signature fails here rather than in a
 * downstream project.
 *
 * Note: `src/index.d.ts` is generated by `npm run gen-dts` from JSDoc — do
 * not edit it by hand. Fix the JSDoc in the corresponding source file and
 * regenerate.
 *
 * Writing these tests surfaced real defects in the generated output that
 * `npm run check-dts` could not catch, because it runs with
 * `--skipLibCheck` and therefore never type-checks the `.d.ts` itself:
 *   - `@returns {Promise<Array>}` emitted a bare `Array` with no type argument
 *   - `@returns {Promise<SitemapJson>}` referenced a typedef the generator
 *     never emits (multi-line typedefs are dropped)
 *   - `@template T, R` params were referenced but never declared
 * All three are fixed at the JSDoc source; keep them fixed.
 */
import { expectType } from "tsd";
import {
  initCMS,
  destroy,
  type InitOptions,
  buildNav,
  type NavBuildResult,
  createSiteNav,
  type NavTreeItem,
  prepareArticle,
  type ArticleResult,
  type ParsedPage,
  type TocEntry,
  parseMarkdownToHtml,
  addMarkdownExtension,
  type MarkdownPlugin,
  slugify,
  normalizePath,
  isExternalLink,
  buildPageUrl,
  generateSitemapJson,
  setMetaTags,
  t,
  currentLang,
} from "./index.js";

// --- Lifecycle ---------------------------------------------------------------

expectType<Promise<void>>(initCMS({ el: "#app" }));
expectType<Promise<void>>(destroy());

const options: InitOptions = {
  el: "#app",
  contentPath: "/content/",
  searchIndex: true,
  cacheTtlMinutes: 5,
  lang: "en",
};
expectType<InitOptions>(options);

// --- Navigation --------------------------------------------------------------

expectType<Promise<NavBuildResult>>(
  buildNav(
    document.createElement("div"),
    document.createElement("div"),
    "<nav></nav>",
    "/content/",
    "index",
    (key) => key,
    () => {},
    true,
    "lazy",
  ),
);

expectType<NavTreeItem[]>(createSiteNav("index"));

const navItem: NavTreeItem = {
  path: "a.md",
  name: "A",
  isIndex: false,
  children: [],
};
expectType<NavTreeItem>(navItem);

// --- Markdown / article rendering -------------------------------------------

expectType<Promise<ArticleResult>>(
  prepareArticle(
    (key) => key,
    { raw: "# Title", isHtml: false },
    "page.md",
    null,
    "/content/",
  ),
);

const parsedPage: ParsedPage = { html: "", meta: {}, toc: [] };
expectType<ParsedPage>(parsedPage);

const tocEntry: TocEntry = { level: 2, text: "Heading", id: "heading" };
expectType<TocEntry>(tocEntry);

expectType<Promise<ParsedPage>>(parseMarkdownToHtml("# Title"));

expectType<void>(addMarkdownExtension({} as MarkdownPlugin));

// --- Slug and URL helpers ----------------------------------------------------

expectType<string>(slugify("Some Title"));
expectType<string>(normalizePath("/a//b/"));
expectType<boolean>(isExternalLink("https://example.com"));
expectType<string>(buildPageUrl("page", "anchor", ""));

// --- Sitemap -----------------------------------------------------------------

expectType<Promise<{ generatedAt: string; entries: Array<any> }>>(
  generateSitemapJson({ index: [] }),
);

// --- SEO and i18n ------------------------------------------------------------

expectType<void>(setMetaTags({ title: "T" }));
expectType<string>(t("some.key", { name: "value" }));
expectType<string>(currentLang);

// --- Negative assertions: the API must not accept nonsense -------------------

// @ts-expect-error `el` is required
initCMS({});

// @ts-expect-error `searchIndex` is a boolean, not a string
initCMS({ el: "#app", searchIndex: "yes" });

// @ts-expect-error `homePage` is not part of InitOptions
initCMS({ el: "#app", homePage: "index" });

// @ts-expect-error slugify takes a string
slugify(42);

// @ts-expect-error normalizePath takes a string, not a number
normalizePath(42);

// @ts-expect-error buildPageUrl requires all three arguments
buildPageUrl("page");
