// Type definitions for nimbiCMS_pre
// Generated by scripts/gen-dts.js; run `npm run gen-dts` to refresh


export type NavTreeItem = { path: string, name: string, isIndex?: boolean, children?: NavTreeItem[] }
export type NavBuildResult = { navbar: HTMLElement, linkEls: NodeListOf<Element> }
export function createSiteNav(homePage: string): NavTreeItem[]
export function buildNav(navbarWrap: HTMLElement, container: HTMLElement, navHtml: string, contentBase: string, homePage: string, t: (key:string, vars?:Record<string,unknown>)=>string, renderByQuery: ()=>void, effectiveSearchEnabled: boolean, searchIndexMode: 'eager'|'lazy'): Promise<NavBuildResult>

export type NavItem = { path: string, name: string, children?: NavItem[] }
export type TocEntry = { level:number, text:string, id?:string }
export type ParsedPage = { html: string, meta: object, toc: TocEntry[] }
export type ArticleResult = { article: HTMLElement, parsed: ParsedPage, toc: HTMLElement, topH1: HTMLElement | null, h1Text: string | null, slugKey: string | null }
export function createNavTree(t: (key:string, vars?:Record<string,unknown>)=>string, tree: NavItem[]): HTMLElement
export function buildTocElement(t: (key:string)=>string, toc: TocEntry[], pagePath?: string): HTMLElement
export function prepareArticle(t: (key:string)=>string, data: {raw:string,isHtml?:boolean}, pagePath: string, anchor: string|null, contentBase: string): Promise<ArticleResult>
export function initAnchorWorker(): Worker|null
export function rewriteAnchorsWorker(article: HTMLElement, contentBase: string, pagePath?: string): Promise<void>
export function attachTocClickHandler(toc: HTMLElement): void
export function scrollToAnchorOrTop(anchor: string|null): void
export function ensureScrollTopButton(article: HTMLElement, topH1: HTMLElement|null, opts?: { mountOverlay?: HTMLElement|null, container?: HTMLElement|null, mountEl?: HTMLElement|null, navWrap?: HTMLElement|null, t?: Function }): void

export type MarkdownPlugin = { tokenizer?: Function, renderer?: object, walkTokens?: Function, transform?: Function }
export const markdownPlugins: MarkdownPlugin[]
export function addMarkdownExtension(plugin: MarkdownPlugin): void
export function setMarkdownExtensions(plugins: MarkdownPlugin[]): void
export function initRendererWorker(): Worker|null
export function parseMarkdownToHtml(md: string): Promise<ParsedPage>
export function detectFenceLanguages(md: string, supportedMap?: Map<string,string>): Set<string>

export const currentLang: string
export function t(key: string, replacements?: Record<string,string>): string

export function setTag(name: string, content: string): void
export function setMetaTags(data: Record<string,unknown>, titleOverride?: string, imageOverride?: string, descOverride?: string, initialDocumentTitle?: string): void
export function setStructuredData(data: Record<string,unknown>, pagePath: string, titleOverride?: string, imageOverride?: string, descOverride?: string, initialDocumentTitle?: string): void
export function applyPageMeta(t: (key:string, vars?:Record<string,unknown>)=>string, initialDocumentTitle: string, parsed: ParsedPage, toc: TocEntry[], article: HTMLElement, pagePath: string, anchor: string|null, topH1: HTMLElement|null, h1Text: string|null, slugKey: string|null, data: Record<string,unknown>): void

export function setLazyload(img: HTMLImageElement): void
export function joinPaths(...parts: string[]): string



export function _clearIndexCache(): void
export function refreshIndexPaths(): void
export function _purgeExpiredEntries(): void
export function buildPageCandidates(resolved: string): string[]
export function fetchPageData(raw: string, contentBase: string): Promise<{data: Record<string, any>, pagePath: string, anchor: string | null}>

export function initSlugWorker(): Worker|null
export function addSlugResolver(fn: (slug:string,contentBase?:string)=>Promise<string|null>|string|null): void
export const notFoundPage: string
export function setContentBase(contentBase: string): void
export function slugify(s: string): string
export function resolveSlugPath(slug: string): string|null
export const crawlCache: Map<string, Promise<string|null>|string|null>
export function buildSearchIndex(contentBase: string): Promise<Array<{slug:string,title:string,excerpt:string,path:string}>>
export function setDefaultCrawlMaxQueue(n: number): void
export const crawlForSlug: (decoded: string, contentBase: string, maxQueue?: number) => Promise<string|null>
export function crawlAllMarkdown(contentBase: string, maxQueue: number): Promise<string[]>
export function ensureSlug(decoded: string, contentBase: string, maxQueue: any): Promise<string|null>


export type ThemeStyle = 'light' | 'dark'

export interface InitOptions {
  el: string | Element
  contentPath?: string
  crawlMaxQueue?: number
  searchIndex?: boolean
  cacheTtlMinutes?: number
  defaultStyle?: ThemeStyle
  bulmaCustomize?: string
  lang?: string
  l10nFile?: string | null
  /** optional array of markdown paths provided by the host (example plugin)
   *  used by slug resolution and search index */
  markdownPaths?: string[]
}

export interface PageContext {
  data: Record<string, any>
  pagePath: string
  anchor: string | null
}

export interface HookContext {
  // common fields provided to all hooks
  pagePath?: string
  anchor?: string | null
  article?: HTMLElement
  toc?: HTMLElement
  topH1?: HTMLElement | null
  h1Text?: string | null
  slugKey?: string | null
  data?: Record<string, any>
  contentWrap?: HTMLElement | null
  navWrap?: HTMLElement | null
  // nav-build specific
  navbar?: HTMLElement
  linkEls?: NodeListOf<HTMLAnchorElement>
  contentBase?: string
}

// UI helper option and return shapes (mirrors src/ui.js typedefs)
export type UIOptions = {
  contentWrap: HTMLElement,
  navWrap: HTMLElement,
  container: HTMLElement,
  mountOverlay?: HTMLElement | null,
  t: (key: string, vars?: Object)=>string,
  contentBase: string,
  homePage: string,
  initialDocumentTitle: string,
  runHooks: (name: string, ctx?: Object)=>void|Promise<void>
}

export type UIReturn = {
  renderByQuery: () => Promise<void>,
  siteNav: object,
  getCurrentPagePath: () => string | null
}

// Router resolution cache types
export type ResolutionRecord = { value: { resolved: string, anchor: string | null }, ts: number }
export const RESOLUTION_CACHE_MAX: number
export const RESOLUTION_CACHE_TTL: number
export function setResolutionCacheMax(n: number): void
export function setResolutionCacheTtl(ms: number): void
export const resolutionCache: Map<string, ResolutionRecord>

// Fetch result and localization entry shapes (from slugManager and l10n defaults)
export type FetchResult = { raw: string, isHtml?: boolean, status?: number }
export type L10nEntry = { navigation: string, onThisPage: string, home: string, scrollToTop: string, readingTime: string, searchPlaceholder: string }

// primary entrypoint – options object is strongly typed above
export function initCMS(options: InitOptions): Promise<void>
export default initCMS

// hook / plugin API definitions
export function addHook(name: string, fn: (ctx:HookContext)=>void|Promise<void>): void
export function onPageLoad(fn: (ctx:HookContext)=>void|Promise<void>): void
export function onNavBuild(fn: (ctx:HookContext)=>void|Promise<void>): void
export function transformHtml(fn: (ctx:HookContext)=>void|Promise<void>): void
export function _clearHooks(): void

export type WorkerManager = {
  get: () => Worker | null
  send: (msg: any, timeout?: number) => Promise<unknown>
  terminate: () => void
}

// Worker manager helpers
export function makeWorkerManager(createWorker: () => Worker|null, name?: string): WorkerManager
export function createWorkerFromRaw(code: string): Worker|null

// UI helper (opaque options for now)
export function createUI(opts: UIOptions): UIReturn

// Slug manager shared maps
export const slugToMd: Map<string, string|{default?:string,langs?:Record<string,string>}>
export const mdToSlug: Map<string,string>
export const availableLanguages: string[]
export const listPathsFetched: Set<string>
export const listSlugCache: Map<string,string>
export const searchIndex: Array<{slug:string,title:string,excerpt:string,path:string}>

// Codeblocks
export const SUPPORTED_HLJS_MAP: Map<string,string>

// Additional explicit declarations to reduce remaining any entries
export function setLanguages(list: string[]): void
export function buildSearchIndexWorker(contentBase: string): Promise<Array<{slug:string,title:string,excerpt:string,path:string}>>
export function crawlForSlugWorker(slug: string, base: string, maxQueue: number): Promise<string|null>
export function removeSlugResolver(fn: (slug:string)=>unknown): void
export function setNotFoundPage(p: string): void
export function _setAllMd(obj: Record<string,string>): void
export function clearListCaches(): void
export function clearFetchCache(): void
export function fetchMarkdown(path: string, base?: string): Promise<FetchResult>



// --- from src/worker-manager.js



// --- from src/version.js


// --- from src/ui.js


// --- from src/slugManager.js
export function setSkipRootReadme(v: any): any
export const skipRootReadme: boolean
export function getLanguages(): string[]
export function _storeSlugMapping(slug: string, rel: string): void
export function setHomePage(p: string): any
export function isExternalLink(href: string): boolean
export function isExternalLinkWithBase(href: string, contentBase: string): boolean
export function unescapeMarkdown(s: string): string
export function setFetchMarkdown(fn: (path:string, base?:string)=>Promise<FetchResult>): any


































// --- from src/seoManager.js
export function getSiteNameFromMeta(): string





// --- from src/router.js
export function augmentIndexWithAllMarkdownPaths(arrOrMap: any): any












// --- from src/nimbi-cms.js

// --- from src/nav.js



// --- from src/markdown.js







// --- from src/l10nManager.js
export function loadL10nFile(path: string, pageDir: string): Promise<void>
export function setLang(lang: string): void



// --- from src/init.js
export function parseInitOptionsFromQuery(queryString: string): object
export const currentHighlightTheme: any
export const initialDocumentTitle: string


// --- from src/indexManager.js



// --- from src/imagePreview.js
export function attachImagePreview(opts: any): any

// --- from src/htmlBuilder.js
export function preScanHtmlSlugs(linkEls: NodeListOf<HTMLAnchorElement>, base: string): Promise<void>
export function preMapMdSlugs(linkEls: NodeListOf<HTMLAnchorElement>|HTMLAnchorElement[], contentBase: string): Promise<void>
export function executeEmbeddedScripts(article: any): any
export function renderNotFound(contentWrap: HTMLElement|null, t: Function|null, e: Error|null): any









// --- from src/hookManager.js
export function runHooks(name: string, ctx: object): Promise<void>






// --- from src/gen-dts-sample.js
export function complexExample(opts: {a:number,b:string}): Promise<Array<{foo:string}|{bar:number}>>
export function simpleUnion(): string|number
export function recordExample(): Record<string, number[]>
export function sum(opts: any): {sum:number}
export function callIt(cb: (...args:any[])=>any): void

// --- from src/codeblocksManager.js
export const HLJS_ALIAS_MAP: Record<string,string>
export function loadSupportedLanguages(url: string): Promise<void>
export function registerLanguage(name: string, modulePath: string): Promise<boolean>
export function observeCodeBlocks(root: any): void
export function setHighlightTheme(opts: {useCdn?:boolean}): void



// --- from src/bulmaManager.js
export function ensureBulma(bulmaCustomize: string, pageDir: string): Promise<void>
export function setStyle(style: 'light'|'dark'): void
export function setThemeVars(vars: Record<string,string>): void
export function registerThemedElement(el: any): () => void

// --- from src/worker/slugWorker.js

// --- from src/worker/renderer.js

// --- from src/worker/anchorWorker.js

// --- from src/utils/l10n-defaults.js
export const DEFAULT_L10N: Record<string, L10nEntry>


// --- from src/utils/helpers.js
export function normalizePath(p: string): string
export function trimTrailingSlash(u: string): string
export function ensureTrailingSlash(u: string): string
export function setEagerForAboveFoldImages(container: any, marginPx: number, debug: boolean): any
export function encodeURL(u: string): string
export function safe(fn: () => any|Promise<any>): any|Promise<any>|undefined




// --- from src/utils/frontmatter.js
export function parseFrontmatter(md: string): {content:string, data: Record<string,string>}

// --- from src/lib/index.js
