// Type definitions for nimbiCMS_pre
// Generated by scripts/gen-dts.js; run `npm run gen-dts` to refresh


export type ThemeStyle = 'light' | 'dark'

export interface InitOptions {
  el: string | Element
  contentPath?: string
  defaultStyle?: ThemeStyle
  bulmaCustomize?: string
  lang?: string
  l10nFile?: string | null
  /** optional array of markdown paths provided by the host (example plugin)
   *  used by slug resolution and search index */
  markdownPaths?: string[]
}

export interface PageContext {
  data: any
  pagePath: string
  anchor: string | null
}

export interface HookContext {
  // common fields provided to all hooks
  pagePath?: string
  anchor?: string | null
  article?: HTMLElement
  toc?: HTMLElement
  topH1?: HTMLElement | null
  h1Text?: string | null
  slugKey?: string | null
  data?: any
  contentWrap?: HTMLElement | null
  navWrap?: HTMLElement | null
  // nav-build specific
  navbar?: HTMLElement
  linkEls?: NodeListOf<HTMLAnchorElement>
  contentBase?: string
}

// primary entrypoint – options object is strongly typed above
export function initCMS(options: InitOptions): Promise<void>
export default initCMS

export function addSlugResolver(fn: any): any
export const slugToMd: any
export const mdToSlug: any
export function removeSlugResolver(fn: any): any
export function _setAllMd(obj: Object<string,string>): any
export const listSlugCache: any
export function clearListCaches(): any
export function setContentBase(contentBase: string): any
export function slugify(s: any): string
export const fetchCache: any
export function clearFetchCache(): any
export const fetchMarkdown: any
export function buildSearchIndex(contentBase: string): Promise<Array<{slug:string,title:string,excerpt:string,path:string}>>
export function setDefaultCrawlMaxQueue(n: number): any
export const crawlForSlug: any
export function crawlAllMarkdown(contentBase: string, maxQueue: number): Promise<string[]>
export function ensureSlug(decoded: string, contentBase: string, maxQueue: any): Promise<string|null>







export function setMetaTags(data: object, titleOverride: string, imageOverride: string, descOverride: string, initialDocumentTitle: string): any
export function getSiteNameFromMeta(): string|null
export function setStructuredData(data: object, pagePath: string, titleOverride: string, imageOverride: string, descOverride: string, initialDocumentTitle: string): any
export function applyPageMeta(t: any, initialDocumentTitle: string, parsed: object, toc: any, article: any, pagePath: string, anchor: string|null, topH1: HTMLElement|null, h1Text: string|null, slugKey: string|null, data: object): any

export const resolutionCache: any
export function _clearIndexCache(): any
export function refreshIndexPaths(): any
export function resolutionCacheGet(key: string): {resolved:string,anchor:string|null}|undefined
export function resolutionCacheSet(key: string, value: {resolved:string},anchor:string|null): any
export function buildPageCandidates(resolved: string): string[]
export function fetchPageData(raw: string, contentBase: string): Promise<{data:object,pagePath:string,anchor:string|null}>

export function addHook(name: any, fn: any): any
export function onPageLoad(fn: any): any
export function onNavBuild(fn: any): any
export function transformHtml(fn: any): any
export function _clearHooks(): Promise<void>


export function parseMarkdownToHtml(md: string): Promise<{html:string,meta:Object,toc:Array<{level:number,text:string,id:string}>}>
export function detectFenceLanguages(md: string, supportedMap: Map<string,string>): Set<string>
export function t(key: string, replacements: object): string
export function loadL10nFile(path: string, pageDir: string): Promise<void>
export function setLang(lang: string): any

export function createNavTree(t: any, tree: {path:string,name:string,children?:any[]}[]): any
export function buildTocElement(t: any, toc: {level:number,text:string,id?:string}[], pagePath: string): any
export function preScanHtmlSlugs(linkEls: NodeListOf<HTMLAnchorElement>, base: string): any
export function preMapMdSlugs(linkEls: NodeListOf<HTMLAnchorElement>|HTMLAnchorElement[], contentBase: string): Promise<void>
export function prepareArticle(t: any, data: {raw:string,isHtml?:boolean}, pagePath: string, anchor: string|null, contentBase: string): Promise<{article:HTMLElement,parsed:Object,toc:HTMLElement,topH1:HTMLElement|null,h1Text:string|null,slugKey:string|null}>
export function attachTocClickHandler(toc: any): any
export function scrollToAnchorOrTop(anchor: string|null): any
export function ensureScrollTopButton(article: any, topH1: HTMLElement|null, opts: object, container: any, mountEl: any, navWrap: any, t: any): any

export function loadSupportedLanguages(url: string): Promise<void>
export function registerLanguage(name: string, modulePath: string): Promise<boolean>
export function observeCodeBlocks(root: any): any
export function setHighlightTheme(theme: string, opts: {useCdn?:boolean}): any



export function ensureBulma(bulmaCustomize: string, pageDir: string): Promise<void>
export function setStyle(style: 'light'|'dark'): any
export function setThemeVars(vars: Record<string,string>): any


export function isExternalLink(href: string): boolean
export function normalizePath(p: string): string
export function trimTrailingSlash(u: string): string
export function ensureTrailingSlash(u: string): string
export function setLazyload(img: any): any
export function joinPaths(...parts: any): string
export function encodeURL(u: string): string
export function safe(fn: any): any

